version: '3'
services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_DB_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_DB_PASS}"
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5436:5432
    volumes:
      - ${PATH_TO_DATABASE}:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  transactions-proxy-backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SERVER_PORT: "${SERVER_PORT}"
      CNODE_ADDRESS: "${CNODE_ADDRESS}"
      POSTGRES_DB_HOST: "postgres"
      POSTGRES_DB_PORT: "5432"
      POSTGRES_DB_USER: "${POSTGRES_DB_USER}"
      POSTGRES_DB_PASS: "${POSTGRES_DB_PASS}"
      POSTGRES_DB_NAME: "${POSTGRES_DB_NAME}"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
